### ISSUE TITLE
Abandoned?

### ISSUE THREAD

**Issue by jamesdube** [Daniel15/Sharpamp#1]
Are you still working on this project?

**Comment by Daniel15** [comment]
I'm not working on it any more. It might still work though :smile:  I haven't tested it with newer versions of Winamp nor with newer versions of Visual Studio.

I just realised I didn't copy over the installer from Google Code. I'll see if I can find a copy of it.

**Comment by jamesdube** [comment]
Ok , i hope you do find it. I want to finish off a plugin i started some few years back using your C# api, i hope to release it with Winamp 6. It if ever gets released lol

**Comment by jamesdube** [comment]
I've been searching for the setup, cant find it....would really appreciate if you could find it for me

**Comment by Daniel15** [comment]
I wrote to Google to get a copy of the download, and heard back from them. I've just uploaded it to Github now: https://github.com/Daniel15/Sharpamp/releases/download/release-0.1.0/Sharpamp.0.1.Beta.exe

Note that I believe it only installs the template for Visual Studio 2008 and 2010, you'll need to manually copy it to the right directory for newer VS versions. Also I haven't tested in anything newer than VS2008 :)

**Comment by jamesdube** [comment]
Thanks a lot! I just noticed yesterday. I did also notice too it wont install automatically for VS > 2010 , but its not an issue. I'll definitely let you  know once i finish my plugin....and not to forget the credit for Sharpamp !!
